/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/c089bb7d-f067-45dc-9213-765015344c93 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String iotData;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/



#include "thingProperties.h"

#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#define SCREEN_ADDRESS 0x3C
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define FONT_SIZE1 1
#define FONT_SIZE2 2
#define FONT_COLOR WHITE
#define DISTANCE_TOP 23
#define DISTANCE_LEFT 0
#define LOGO_DISTANCE_TOP DISTANCE_TOP +  26
#define LOGO_DISTANCE_LEFT DISTANCE_LEFT + 68
// On an arduino UNO:       A4(SDA), A5(SCL)
// On an arduino MEGA 2560: 20(SDA), 21(SCL)
// On an arduino LEONARDO:   2(SDA),  3(SCL)
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

String str = "ABCDEF";
int i = 0;


void setup() {
  Serial.begin(9600);

  if(!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS)) { Serial.println(F("SSD1306 allocation failed")); for(;;); }
 display.setRotation(2);
  delay(2000);
  
  display.clearDisplay();
  display.setTextSize(FONT_SIZE2);
  display.setTextColor(FONT_COLOR);
  display.setCursor(DISTANCE_LEFT, DISTANCE_TOP);
  display.println(str);// Display static text
  display.display(); 
  PrintLcd();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since Data is READ_WRITE variable, onDataChange() is
  executed every time a new value is received from IoT Cloud.
*/

void PrintLcd(){
  display.clearDisplay();
  display.setTextSize(FONT_SIZE2);
  display.setCursor(5, 1);
  display.println("IOT Server");
  display.setCursor(DISTANCE_LEFT, DISTANCE_TOP);
  display.println(str);// Display static text
  
  display.setTextSize(FONT_SIZE1);
  display.setCursor(LOGO_DISTANCE_LEFT, LOGO_DISTANCE_TOP);
  display.println("ArthurCam");
  display.setCursor(LOGO_DISTANCE_LEFT + 28, LOGO_DISTANCE_TOP + 8);
  display.println(".com");
  
  display.setCursor(DISTANCE_LEFT, LOGO_DISTANCE_TOP);
  display.println(i >= 10 ? String(i) : "0" + String(i) );
  display.println("  sec");
  i %= 59;
  ++i;
  display.display(); 
  delay(1000);
}



void onDataChange()  {
  // Add your code here to act upon Data change
}


/*
  Since IotData is READ_WRITE variable, onIotDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIotDataChange()  {
  // Add your code here to act upon IotData change
  str = iotData;
  PrintLcd();
}