/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/c089bb7d-f067-45dc-9213-765015344c93 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String iotData;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#define LED1 3

#include "thingProperties.h"

void setup() {
  pinMode(LED1, OUTPUT);
  
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since Data is READ_WRITE variable, onDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDataChange()  {
  // Add your code here to act upon Data change
}


/*
  Since IotData is READ_WRITE variable, onIotDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIotDataChange()  {
  // Add your code here to act upon IotData change
  digitalWrite(LED1, !digitalRead(LED1));
}